## 26 Feb Assignment Solution

In [1]:
import numpy as np

In [2]:
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list?
If there is then write a code to print the data types of both the variables.

In [3]:
print(list_)
# This the a normal list that we use in python
# It's data types is <class 'list'>
# No new library is required for this
print(type(list_))

['1', '2', '3', '4', '5']
<class 'list'>


In [4]:
print(array_list)
# This is an numpy array
# It's data types is <class 'numpy.ndarray'>
# We need to import numpy to use this
print(type(array_list))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [5]:
# array_list
array_list.dtype

dtype('<U1')

In [6]:
for i in array_list: print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [7]:
# list_
for i in list_: print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [8]:
array_list = np.array(object = list_, dtype = int)

In [9]:
array_list.dtype
# This types has been changes form Str(Unicode string) to Integer

dtype('int64')

In [10]:
# Consider the below code to answer further questions:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:

In [11]:
# (i) shape
num_array.shape

(2, 3)

In [12]:
# (ii) size

In [13]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only,
using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.matrix(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])